### ISSUE TITLE
Refactoring warnings

### ISSUE THREAD

**Issue by JasperBerton** [davidvlaminck/OTLMOW-Model#31]
Nodige refactoring van warnings zodat deze volgend Single Responsibility worden uitgevoerd & zodat deze beter getest kunnen worden. 

in de testklasse ziet dit er dan zo uit:
`with pytest.warns(GegooideWarning):
        instance.attribuut = waardeDieWarningGooit`

effectief voorbeeld: DateFieldAttribute_test.py lijn 27-28

code waar de warning gesmeten word:

` 
warnings.warn( 'Bericht bij warning', GegooideWarning)
`

effectief voorbeeld: DateField.py lijn 26-27 
**warnings moet in deze klassen geïmporteerd worden!**

bij gebruik van een nieuwe warning ook een nieuwe klasse aanmaken in de warnings folder zoals IncorrectTypeWarning.py

**Comment by davidvlaminck** [comment]
fixed for DateField in https://github.com/davidvlaminck/OTLMOW-Model/commit/6730de6c0237bc9a748894dbffd491597a2e1408
