### ISSUE TITLE
 new relations to objects already in DAVIE do not have bronTypeUri or targetTypeUri

### ISSUE THREAD

**Issue by christiaan20** [davidvlaminck/OTLMOW-Model#58]
OtlmowModel/Helpers/RelationCreator.py at line 158
This causes new relations to objects already in DAVIE to not have their bronTypeUri or targetTypeUri filled in causing them to be rejected by the OTL-wizard
```  
# TODO replace check with check for format of AIM id, if False, add typeURI
    if relation_type.bronAssetId.toegekendDoor != 'AWV':
        relation_type.bron.typeURI = source.typeURI
    if relation_type.doelAssetId.toegekendDoor != 'AWV':
        relation_type.doel.typeURI = target.typeURI
```

Shouldn’t this be checking the if the id of the relation itself is an IAM id ?
Or maybe no check is needed because new relation object always need their doel or bron typeURI

**Comment by davidvlaminck** [comment]
reconstruct case:
assets both toegekendDoor = 'AWV' but the relation not
