### ISSUE TITLE
changing the typeURI attribute of a class should raise an Exception with a clear message

### ISSUE THREAD

**Issue by davidvlaminck** [davidvlaminck/OTLMOW-Model#6]
Changing the typeURI of an asset is not possible.
Check to see if this raises an Exception and edit it so that it informs the user this is not allowed and why not

**Comment by rudewi** [comment]
my suggestion for a warning would be this (based on the 'instructiebundel' info): "The typeURI is an OSLOAttribute that indicates the class of the instance. Within a class this value is predefined and cannot be changed."
